//HintName: TemplateGeneratorLog.g.cs
// AutoGenerated log file.

// [2025-05-29T20:07:07.6716312+02:00 | Trace] Registering generator 'EngineGenerator'
// [2025-05-29T20:07:07.6741959+02:00 | Trace] Registering generator 'PipelineGenerator'
// [2025-05-29T20:07:07.7363384+02:00 | Trace] Generator 'EngineGenerator' will be run on node at 'SourceFile([1996..2010))'
// [2025-05-29T20:07:07.7397186+02:00 | Trace] Generator 'PipelineGenerator' will be run on node at 'SourceFile([1996..2010))'
// [2025-05-29T20:07:07.7552475+02:00 | Trace] Executing generator 'Component Generator (Test.HengineEcs) (SourceFile([1996..2010)))'
// [2025-05-29T20:07:07.8029504+02:00 | Trace] Generator finished
// [2025-05-29T20:07:07.8182385+02:00 | Trace] Executing generator 'Component Generator (Test.HengineEcs) (SourceFile([1992..2852)))'
// [2025-05-29T20:07:07.8228082+02:00 | Trace] Generator finished
