//HintName: TemplateGeneratorLog.g.cs
//--- AutoGenerated info file. ---

//--- Log: ---

// [2026-01-25T14:25:51.9847344+01:00 | Trace] Registering generator 'EngineGenerator'
// [2026-01-25T14:25:51.9873381+01:00 | Trace] Registering generator 'PipelineGenerator'
// [2026-01-25T14:25:52.0532926+01:00 | Trace] Generator 'EngineGenerator' will be run on node at 'SourceFile([1996..2010))'
// [2026-01-25T14:25:52.0569085+01:00 | Trace] Generator 'PipelineGenerator' will be run on node at 'SourceFile([1996..2010))'
// [2026-01-25T14:25:52.0712707+01:00 | Trace] Executing generator 'Component Generator (Test.HengineEcs) (SourceFile([1996..2010)))'
// [2026-01-25T14:25:52.1234875+01:00 | Trace] Generator finished
// [2026-01-25T14:25:52.1378780+01:00 | Trace] Executing generator 'Component Generator (Test.HengineEcs) (SourceFile([1992..2852)))'
// [2026-01-25T14:25:52.1420938+01:00 | Trace] Generator finished
