//HintName: TemplateGeneratorLog.g.cs
//--- AutoGenerated info file. ---

//--- Log: ---

// [2026-01-25T13:49:14.2568548+01:00 | Trace] Registering generator 'EngineGenerator'
// [2026-01-25T13:49:14.2593184+01:00 | Trace] Registering generator 'PipelineGenerator'
// [2026-01-25T13:49:14.3300898+01:00 | Trace] Generator 'EngineGenerator' will be run on node at 'SourceFile([1996..2010))'
// [2026-01-25T13:49:14.3337645+01:00 | Trace] Generator 'PipelineGenerator' will be run on node at 'SourceFile([1996..2010))'
// [2026-01-25T13:49:14.3499095+01:00 | Trace] Executing generator 'Component Generator (Test.HengineEcs) (SourceFile([1996..2010)))'
// [2026-01-25T13:49:14.4066440+01:00 | Trace] Generator finished
// [2026-01-25T13:49:14.4226923+01:00 | Trace] Executing generator 'Component Generator (Test.HengineEcs) (SourceFile([1992..2852)))'
// [2026-01-25T13:49:14.4272243+01:00 | Trace] Generator finished
